name: sphinx-publish
on:
  push:
    branches:
      - 'publish'
jobs:
  sphinx-publish:
    runs-on: ubuntu-latest
    steps:

      # clone and checkout the branch/commit that triggered the workflow
      - uses: actions/checkout@v3

      # create the conda environment and activate it
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: '*'
          environment-file: spellbook.yml
          activate-environment: spellbook

      # Activate spellbook environment and freeze to requirements.txt
      # - use `pip list --format=freeze > requirements.txt` because
      #   of https://stackoverflow.com/a/62886215
      - name: Conda activate spellbook
        shell: bash -l {0}
        run: |
          conda env list
          conda activate spellbook
          conda info
          conda list
          echo $GITHUB_WORKSPACE
          pip list --format=freeze > requirements.txt
          pwd
          ls -lAh
          cat requirements.txt

      - name: Set python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check python version
        run: |
          which python
          python --version

      - name: build and commit
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: doc/source
          target_path: docs
          requirements_path: requirements.txt

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages